/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Account;
import controller.FirstView;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class LoginView extends javax.swing.JFrame {

    ImageIcon anh = new ImageIcon("shopPink.jpg");
    public LoginView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(FirstView.icon.getImage());
        jlbImage.setIcon(anh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbUser = new javax.swing.JLabel();
        jlbPassword = new javax.swing.JLabel();
        jtfTK = new javax.swing.JTextField();
        jlbTitle = new javax.swing.JLabel();
        jpfMK = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jlbImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shopping Online Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbUser.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlbUser.setText("User ID");
        getContentPane().add(jlbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, -1));

        jlbPassword.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlbPassword.setText("Password");
        getContentPane().add(jlbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jtfTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTKActionPerformed(evt);
            }
        });
        getContentPane().add(jtfTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, -1));

        jlbTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlbTitle.setText("Login");
        jlbTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        getContentPane().add(jlbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jpfMK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jpfMK.setText("1234");
        getContentPane().add(jpfMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, -1));

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 80, 30));

        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBack.setText("<< Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        getContentPane().add(jlbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String tk = jtfTK.getText();
        String mk = jpfMK.getText();
        String s="";
        boolean check = false;
        Account ac = new Account(tk,mk);
        for (Account ele : FirstView.da.getTotalAc()) {           
            if(ele.equals(ac)){
                JOptionPane.showMessageDialog(this, "Login Successfully!");
                check = true;
                MainView vs = new MainView();
                vs.setVisible(true); pack();
                this.dispose();
            }
        }
        
        if(check==false) JOptionPane.showMessageDialog(this, "User,Password is wrong!");

    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        FirstView fv = new FirstView();
        fv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jtfTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jlbImage;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JLabel jlbUser;
    private javax.swing.JPasswordField jpfMK;
    private javax.swing.JTextField jtfTK;
    // End of variables declaration//GEN-END:variables
}
