/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Cart;
import Model.Order;
import controller.ConvertSwingFunction;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class OrderJP extends javax.swing.JPanel {
    private Cart gio;
    
    public OrderJP() {
        initComponents();
        this.gio = ConvertSwingFunction.ca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOrder = new javax.swing.JPanel();
        jpnCusInform = new javax.swing.JPanel();
        jlbName = new javax.swing.JLabel();
        jlbAddress = new javax.swing.JLabel();
        jlbTele = new javax.swing.JLabel();
        jtextName = new javax.swing.JTextField();
        jtextAddress = new javax.swing.JTextField();
        jtextTelephone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonConfirm = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jpnBill = new javax.swing.JPanel();
        jScrollPaneBill = new javax.swing.JScrollPane();
        jtaBill = new javax.swing.JTextArea();
        jButtonSend = new javax.swing.JButton();
        jlbNote = new javax.swing.JLabel();
        jScrollPaneWayPay = new javax.swing.JScrollPane();
        jtaWayPay = new javax.swing.JTextArea();
        jlbTitle = new javax.swing.JLabel();

        jPanelOrder.setBackground(new java.awt.Color(0, 0, 0));

        jpnCusInform.setBackground(new java.awt.Color(153, 255, 204));

        jlbName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbName.setText("Name");
        jlbName.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jlbAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbAddress.setText("Address");
        jlbAddress.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jlbTele.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTele.setText("Telephone");
        jlbTele.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jtextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextNameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Customer Information");

        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpnCusInformLayout = new org.jdesktop.layout.GroupLayout(jpnCusInform);
        jpnCusInform.setLayout(jpnCusInformLayout);
        jpnCusInformLayout.setHorizontalGroup(
            jpnCusInformLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnCusInformLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpnCusInformLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 202, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jpnCusInformLayout.createSequentialGroup()
                        .add(jpnCusInformLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jlbAddress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jlbTele, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jlbName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(18, 18, 18)
                        .add(jpnCusInformLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jpnCusInformLayout.createSequentialGroup()
                                .add(jButtonConfirm)
                                .add(18, 18, 18)
                                .add(jButtonReset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jpnCusInformLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jtextName)
                                .add(jtextAddress)
                                .add(jtextTelephone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jpnCusInformLayout.setVerticalGroup(
            jpnCusInformLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnCusInformLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(32, 32, 32)
                .add(jpnCusInformLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlbName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtextName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(40, 40, 40)
                .add(jpnCusInformLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jlbAddress, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jtextAddress))
                .add(40, 40, 40)
                .add(jpnCusInformLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jlbTele, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jtextTelephone))
                .add(45, 45, 45)
                .add(jpnCusInformLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonConfirm)
                    .add(jButtonReset))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnBill.setBackground(new java.awt.Color(153, 255, 204));

        jtaBill.setColumns(20);
        jtaBill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtaBill.setRows(5);
        jScrollPaneBill.setViewportView(jtaBill);

        jButtonSend.setText("Send");
        jButtonSend.setToolTipText("");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jlbNote.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jlbNote.setText("Note:");

        jtaWayPay.setColumns(20);
        jtaWayPay.setRows(5);
        jScrollPaneWayPay.setViewportView(jtaWayPay);

        jlbTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlbTitle.setText("Bill Pay");

        org.jdesktop.layout.GroupLayout jpnBillLayout = new org.jdesktop.layout.GroupLayout(jpnBill);
        jpnBill.setLayout(jpnBillLayout);
        jpnBillLayout.setHorizontalGroup(
            jpnBillLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnBillLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpnBillLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPaneBill, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .add(jpnBillLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jButtonSend, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jpnBillLayout.createSequentialGroup()
                        .add(jpnBillLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jlbNote, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jScrollPaneWayPay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 242, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpnBillLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jlbTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(161, 161, 161))
        );
        jpnBillLayout.setVerticalGroup(
            jpnBillLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnBillLayout.createSequentialGroup()
                .addContainerGap()
                .add(jlbTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPaneBill, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 296, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButtonSend)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jlbNote)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPaneWayPay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanelOrderLayout = new org.jdesktop.layout.GroupLayout(jPanelOrder);
        jPanelOrder.setLayout(jPanelOrderLayout);
        jPanelOrderLayout.setHorizontalGroup(
            jPanelOrderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpnCusInform, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jpnBill, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOrderLayout.setVerticalGroup(
            jPanelOrderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelOrderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpnCusInform, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jpnBill, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 887, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanelOrder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 574, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(jPanelOrder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextNameActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jtextName.setText("");
        jtextAddress.setText("");
        jtextTelephone.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        if(!gio.getBasket().isEmpty()){
            Order or = new Order();
            or.setCustomer(jtextName.getText());
            or.setAddress(jtextAddress.getText());
            or.setTele(jtextTelephone.getText());
            or.setCart(gio);
            jtaBill.setText(or.toString());
            jtaWayPay.setText("You can switch money to Bank Account:\nBIDV 58010001467581 Huynh Gia \nIf not , you will pay directly when we ship at your home.\nThank! ");
        }else
            JOptionPane.showMessageDialog(this, "Your cart is Empty , please buy product in shop");
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        jtextName.setText("");
        jtextAddress.setText("");
        jtextTelephone.setText("");
        jtaBill.setText("");
        jtaWayPay.setText("");
        gio.getBasket().clear();
    }//GEN-LAST:event_jButtonSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelOrder;
    private javax.swing.JScrollPane jScrollPaneBill;
    private javax.swing.JScrollPane jScrollPaneWayPay;
    private javax.swing.JLabel jlbAddress;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbNote;
    private javax.swing.JLabel jlbTele;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JPanel jpnBill;
    private javax.swing.JPanel jpnCusInform;
    private javax.swing.JTextArea jtaBill;
    private javax.swing.JTextArea jtaWayPay;
    private javax.swing.JTextField jtextAddress;
    private javax.swing.JTextField jtextName;
    private javax.swing.JTextField jtextTelephone;
    // End of variables declaration//GEN-END:variables
}
