/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Account;
import controller.FirstView;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class RegisterView extends javax.swing.JFrame {

    private ImageIcon anh = new ImageIcon("shopPink.jpg");
    public RegisterView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(FirstView.icon.getImage());
        jLabel1.setIcon(anh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbUser = new javax.swing.JLabel();
        jlbPassword = new javax.swing.JLabel();
        jtfTK = new javax.swing.JTextField();
        jlbTitle = new javax.swing.JLabel();
        jpfMK = new javax.swing.JPasswordField();
        jbuttonRegister = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jlbNote = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shopping Online Register");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbUser.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlbUser.setText("User ID");
        getContentPane().add(jlbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, -1));

        jlbPassword.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlbPassword.setText("Password");
        getContentPane().add(jlbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jtfTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfTK.setToolTipText("User includes character are less than 10 digits ");
        getContentPane().add(jtfTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, -1));

        jlbTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlbTitle.setText("Register Account");
        jlbTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        getContentPane().add(jlbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jpfMK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jpfMK.setText("1234");
        jpfMK.setToolTipText("Password includes both character and number , is less than 10 digits");
        getContentPane().add(jpfMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, -1));

        jbuttonRegister.setText("Register");
        jbuttonRegister.setToolTipText("Click here to register");
        jbuttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBack.setText("<< Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jlbNote.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jlbNote.setText("Note:");
        getContentPane().add(jlbNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("+ User is less than 10 digits\nex: kayhuynh , kay123,...\n+ Password includes both character and \nnumber , Not just number , Not just character\n,Not special character and is less than 15 digits\nex: khoi183, 24220abcxyz,...");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 300, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jbuttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonRegisterActionPerformed
        String tk = jtfTK.getText();
        String mk = jpfMK.getText();
        Account ac = new Account(tk,mk);
        if(ac.checkTKMK()==true){
            JOptionPane.showMessageDialog(this, "Register Completely");
            FirstView.da.getTotalAc().add(ac);
            FirstView.da.saveAccount("Account.txt");
            FirstView fv = new FirstView();
            fv.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "User or Password is wrong format");
        }
    }//GEN-LAST:event_jbuttonRegisterActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        FirstView fv = new FirstView();
        fv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbuttonRegister;
    private javax.swing.JLabel jlbNote;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JLabel jlbUser;
    private javax.swing.JPasswordField jpfMK;
    private javax.swing.JTextField jtfTK;
    // End of variables declaration//GEN-END:variables
}
