/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;


import Model.Product;
import Model.ShopProduct;
import Model.VolumnProduct;
import Model.WeightProduct;
import controller.ConvertSwingFunction;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class SearchJP extends javax.swing.JPanel {
    private ShopProduct sp;
    private DefaultTableModel dTable;
    
    public SearchJP() {
        initComponents();
        this.sp=ConvertSwingFunction.shop;
        this.dTable = (DefaultTableModel) jTableShopSearch.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldID = new javax.swing.JTextField();
        jButtonSearchID = new javax.swing.JButton();
        jlbTitle = new javax.swing.JLabel();
        jScrollPaneShopSearch = new javax.swing.JScrollPane();
        jTableShopSearch = new javax.swing.JTable();
        jlbIDEnter = new javax.swing.JLabel();
        jComboBoxRangePrice = new javax.swing.JComboBox<>();
        jButtonSearchPrice = new javax.swing.JButton();
        jlbNote = new javax.swing.JLabel();
        jlbRangePrice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));

        jTextFieldID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jButtonSearchID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSearchID.setText("Search");
        jButtonSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchIDActionPerformed(evt);
            }
        });

        jlbTitle.setBackground(new java.awt.Color(255, 255, 102));
        jlbTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("SEARCH PRODUCT");
        jlbTitle.setOpaque(true);

        jTableShopSearch.setBackground(new java.awt.Color(153, 255, 255));
        jTableShopSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "NSX", "HSD", "Price", "Quantity", "V(ml)", "M(g)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneShopSearch.setViewportView(jTableShopSearch);

        jlbIDEnter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbIDEnter.setText("Enter ID product");

        jComboBoxRangePrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxRangePrice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "less than 50.000đ", "50.000đ to 100.000đ", "100.000đ to 500.000đ", "more than 500.000đ" }));

        jButtonSearchPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSearchPrice.setText("Search");
        jButtonSearchPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchPriceActionPerformed(evt);
            }
        });

        jlbNote.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jlbNote.setText("There are 2 ways to search :");

        jlbRangePrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbRangePrice.setText("By Range Price");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPaneShopSearch))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(199, 199, 199)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jlbIDEnter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jlbRangePrice))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(layout.createSequentialGroup()
                                        .add(jComboBoxRangePrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(jButtonSearchPrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(jTextFieldID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(31, 31, 31)
                                        .add(jButtonSearchID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jlbNote)))
                        .add(0, 194, Short.MAX_VALUE)))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(323, 323, 323)
                .add(jlbTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 248, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jlbTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPaneShopSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 266, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 32, Short.MAX_VALUE)
                .add(jlbNote)
                .add(3, 3, 3)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlbIDEnter)
                    .add(jButtonSearchID))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxRangePrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonSearchPrice, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jlbRangePrice))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButtonSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchIDActionPerformed
        String id = this.jTextFieldID.getText();
        dTable.setRowCount(0);
        Product sph = sp.searchSPbyID(id, sp.getShop());
            if(sph == null) JOptionPane.showMessageDialog(this, "ID not exist");
            else if(sph instanceof VolumnProduct){
                dTable.addRow(new Object[]{sph.getId(),sph.getProductName(),sph.getNSX(),
                sph.getHSD(),sph.getPrice(),sph.getQuantity(),((VolumnProduct) sph).getVolumn(),0});
            }else{
                dTable.addRow(new Object[]{sph.getId(),sph.getProductName(),sph.getNSX(),
                sph.getHSD(),sph.getPrice(),sph.getQuantity(),0,((WeightProduct) sph).getWeight()});
            }        
    }//GEN-LAST:event_jButtonSearchIDActionPerformed

    private void jButtonSearchPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchPriceActionPerformed
        switch(jComboBoxRangePrice.getSelectedIndex()){
            case 0:
               dTable.setRowCount(0);
               ArrayList<Product> list1 = sp.searchSPbyPrice(sp, pro -> pro.getPrice()<50000);
               showTable(list1);
               break;
            case 1:
               dTable.setRowCount(0);
               ArrayList<Product> list2 = sp.searchSPbyPrice(sp, pro -> pro.getPrice()>=50000 && pro.getPrice()<100000);
               showTable(list2);
               break;               
            case 2:
               dTable.setRowCount(0);
               ArrayList<Product> list3 = sp.searchSPbyPrice(sp, pro -> pro.getPrice()>=100000 && pro.getPrice()<500000);
               showTable(list3);
               break;
            case 3:
               dTable.setRowCount(0);
               ArrayList<Product> list4 = sp.searchSPbyPrice(sp, pro -> pro.getPrice()>=500000);
               showTable(list4);
               break;
        }
    }//GEN-LAST:event_jButtonSearchPriceActionPerformed

    public void showTable(ArrayList<Product> list){
        for (Product sp : list) {
            if(sp instanceof VolumnProduct){
                dTable.addRow(new Object[]{sp.getId(),sp.getProductName(),sp.getNSX(),
                sp.getHSD(),sp.getPrice(),sp.getQuantity(),((VolumnProduct) sp).getVolumn(),0});
            }else{
                dTable.addRow(new Object[]{sp.getId(),sp.getProductName(),sp.getNSX(),
                sp.getHSD(),sp.getPrice(),sp.getQuantity(),0,((WeightProduct) sp).getWeight()});
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearchID;
    private javax.swing.JButton jButtonSearchPrice;
    private javax.swing.JComboBox<String> jComboBoxRangePrice;
    private javax.swing.JScrollPane jScrollPaneShopSearch;
    private javax.swing.JTable jTableShopSearch;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JLabel jlbIDEnter;
    private javax.swing.JLabel jlbNote;
    private javax.swing.JLabel jlbRangePrice;
    private javax.swing.JLabel jlbTitle;
    // End of variables declaration//GEN-END:variables
}
