/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Cart;
import Model.Product;
import Model.ShopProduct;
import Model.VolumnProduct;
import Model.WeightProduct;
import controller.ConvertSwingFunction;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ShopJP extends javax.swing.JPanel {
    private ShopProduct sp ;
    private Cart ca;
    private DefaultTableModel dTable;   
    
    public ShopJP() {
        initComponents();
        this.sp = ConvertSwingFunction.shop;
        this.ca = ConvertSwingFunction.ca;
        //dTable = (DefaultTableModel) jTable1.getModel();
        this.showShoptoTable();
    }

    public ShopProduct getSp() {
        return sp;
    }

    public Cart getCa() {
        return ca;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTitle = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jScrollPaneShop = new javax.swing.JScrollPane();
        jTableShop = new javax.swing.JTable();
        jpnBuy = new javax.swing.JPanel();
        jButtonBuy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 255, 204));
        setPreferredSize(new java.awt.Dimension(896, 572));
        setLayout(new java.awt.BorderLayout());

        jpnTitle.setBackground(new java.awt.Color(153, 255, 204));

        jlbTitle.setBackground(new java.awt.Color(255, 255, 102));
        jlbTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("Shop Product");
        jlbTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jlbTitle.setOpaque(true);
        jpnTitle.add(jlbTitle);

        add(jpnTitle, java.awt.BorderLayout.PAGE_START);

        jTableShop.setBackground(new java.awt.Color(153, 255, 255));
        jTableShop.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTableShop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "NSX", "HSD", "Price", "Quantity", "V(ml)", "M(g)", "Buy"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneShop.setViewportView(jTableShop);

        add(jScrollPaneShop, java.awt.BorderLayout.CENTER);

        jpnBuy.setBackground(new java.awt.Color(153, 255, 204));

        jButtonBuy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBuy.setText("Buy");
        jButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpnBuyLayout = new org.jdesktop.layout.GroupLayout(jpnBuy);
        jpnBuy.setLayout(jpnBuyLayout);
        jpnBuyLayout.setHorizontalGroup(
            jpnBuyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnBuyLayout.createSequentialGroup()
                .add(321, 321, 321)
                .add(jButtonBuy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(444, Short.MAX_VALUE))
        );
        jpnBuyLayout.setVerticalGroup(
            jpnBuyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpnBuyLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .add(jButtonBuy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(23, 23, 23))
        );

        add(jpnBuy, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 431));

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 423, Short.MAX_VALUE)
        );

        add(jPanel4, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyActionPerformed
        //String id = this.jTextField1.getText();
        //boolean check = false;
        ArrayList<Product> spSelected = new ArrayList<>();
        for (int i=0; i<dTable.getRowCount();i++) {
            if(dTable.getValueAt(i, 8).equals(Boolean.TRUE)){ 
                Product p = sp.getProductFromShop(dTable.getValueAt(i, 0)+"");
                spSelected.add(p);
                //check = true;
                //dTabel.setRowCount(0);
                //this.showTable();
                //dTabel.setValueAt(Boolean.FALSE, i, 8);
                
                //dTabel.setValueAt(sp.getShop().get(i).getQuantity(), i, 5);
            } 
        }
        int i = 0;
        for (Product p : spSelected) {
            ca.addItem(p,this.sp);
            dTable.setValueAt(Boolean.FALSE, i++, 8);
        }
        dTable.setRowCount(0);
        this.showShoptoTable();
        //if(check == false) JOptionPane.showMessageDialog(this,"ID not exist");
    }//GEN-LAST:event_jButtonBuyActionPerformed
    
    public void showShoptoTable(){
        dTable = new DefaultTableModel(sp.getData(sp.getShop()),new Product().getTitle()){
            @Override
            public boolean isCellEditable(int row, int column) {
                return column==8;           
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if(columnIndex==8) return Boolean.class;
                else return String.class;
            }
            
        };        
        jTableShop.setModel(dTable);
        /*for (Product sp : sp.getShop()) {
            if(sp instanceof VolumnProduct){
                dTable.addRow(new Object[]{sp.getId(),sp.getProductName(),sp.getNSX(),
                sp.getHSD(),sp.getPrice(),sp.getQuantity(),((VolumnProduct) sp).getVolumn(),0,new Boolean(false)});
            }else{
                dTable.addRow(new Object[]{sp.getId(),sp.getProductName(),sp.getNSX(),
                sp.getHSD(),sp.getPrice(),sp.getQuantity(),0,((WeightProduct) sp).getWeight(),new Boolean(false)});
            }
        }*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuy;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPaneShop;
    private javax.swing.JTable jTableShop;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JPanel jpnBuy;
    private javax.swing.JPanel jpnTitle;
    // End of variables declaration//GEN-END:variables
}
