/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DELL
 */
public class BP_view extends javax.swing.JFrame {

    /**
     * Creates new form BP_view
     */
    public BP_view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jl2 = new javax.swing.JLabel();
        jl3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jb1 = new javax.swing.JButton();
        jl4 = new javax.swing.JLabel();
        jb2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BlackPink");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/unnamed.jpg"))); // NOI18N
        getContentPane().add(jl1);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jl2.setText("User name");
        jPanel1.add(jl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jl3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jl3.setText("Password");
        jPanel1.add(jl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jTextField1.setToolTipText("Enter your account");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 180, 30));

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setToolTipText("Password has more 5 characters");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 180, 30));

        jb1.setBackground(new java.awt.Color(255, 255, 0));
        jb1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jb1.setText("Log In");
        jb1.setToolTipText("Enter Log in");
        jb1.setBorderPainted(false);
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        jPanel1.add(jb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jl4.setBackground(new java.awt.Color(0, 0, 0));
        jl4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jl4.setForeground(new java.awt.Color(255, 51, 255));
        jl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl4.setText("BLINKS");
        jl4.setToolTipText("");
        jl4.setOpaque(true);
        jPanel1.add(jl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 170, 40));

        jb2.setBackground(new java.awt.Color(255, 255, 0));
        jb2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jb2.setText("Register");
        jb2.setToolTipText("Enter to Register");
        jb2.setBorderPainted(false);
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        jPanel1.add(jb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 130, 40));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        this.jl4.setText("BLINKS");
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        this.jl4.setText("Register");
    }//GEN-LAST:event_jb2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BP_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BP_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BP_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BP_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BP_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JLabel jl3;
    private javax.swing.JLabel jl4;
    // End of variables declaration//GEN-END:variables
}
