/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewGUI;

import Controller.JCD;
import Model.Book;
import Model.ShopBook;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class AddViewGUI extends javax.swing.JPanel {

    private ShopBook shB;
    private String pathAnh;
    private mainAPP ma;
    
    public AddViewGUI(mainAPP ma) {
        shB = mainAPP.shB;
        this.ma = ma;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFBarcode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFNamebook = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFAuthor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFGenre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFNumberPage = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFQuantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFPrice = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLbAnh = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("<< Back");
        jButton4.setPreferredSize(new java.awt.Dimension(150, 75));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton4);

        jPanel1.add(jPanel11, java.awt.BorderLayout.LINE_START);

        org.jdesktop.layout.GroupLayout jPanel12Layout = new org.jdesktop.layout.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 105, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, java.awt.BorderLayout.LINE_END);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add Book");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel13.add(jLabel1);

        jPanel1.add(jPanel13, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Reset");
        jPanel2.add(jButton2);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setLayout(new java.awt.GridLayout(7, 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Barcode");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jLabel2);

        jTFBarcode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTFBarcode.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jTFBarcode);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Name Book");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jLabel3);

        jTFNamebook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTFNamebook.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jTFNamebook);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Author");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jLabel4);

        jTFAuthor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTFAuthor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jTFAuthor);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Genre");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jLabel5);

        jTFGenre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTFGenre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jTFGenre);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Number Page");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jLabel6);

        jTFNumberPage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTFNumberPage.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jTFNumberPage);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Quantity");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jLabel7);

        jTFQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTFQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jTFQuantity);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Price");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jLabel8);

        jTFPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTFPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(102, 102, 102)));
        jPanel4.add(jTFPrice);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLbAnh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLbAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBook/MoiLanVap.jpg"))); // NOI18N
        jLbAnh.setText("Image");
        jLbAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 130, 1, 140, new java.awt.Color(0, 0, 0)));
        jPanel6.add(jLbAnh, java.awt.BorderLayout.CENTER);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Add image");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 384, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel8, java.awt.BorderLayout.LINE_START);

        org.jdesktop.layout.GroupLayout jPanel9Layout = new org.jdesktop.layout.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 384, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9, java.awt.BorderLayout.LINE_END);

        jPanel5.add(jPanel6);

        jPanel3.add(jPanel5);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String Bcode = jTFBarcode.getText();
            String nameB = jTFNamebook.getText();
            String TGia = jTFAuthor.getText();
            String Genre = jTFGenre.getText();
            Integer numPage = Integer.parseInt(jTFNumberPage.getText());
            Integer sl = Integer.parseInt(jTFQuantity.getText());
            Double price = Double.parseDouble(jTFPrice.getText());
            
            Book b = new Book(Bcode, nameB, TGia, Genre, numPage, sl, price, this.pathAnh);
            shB.getShopSach().add(b);
            new JCD().addBook(b);
            JOptionPane.showMessageDialog(this, "Add Successfully !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Input data");
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser f= new JFileChooser("C:\\Users\\DELL\\Documents\\NetBeansProjects\\BookShopOnline\\src\\ImageBook");
        f.setDialogTitle("Open File");
        f.showOpenDialog(null);
        File nameImage = f.getSelectedFile();
        this.pathAnh = nameImage.getAbsolutePath();
        this.jLbAnh.setIcon(this.ResizeImage(this.pathAnh));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ma.setVisible(true);
        ChoiceAdd ca = new ChoiceAdd(ma);
        ma.getjSplitPane1().setRightComponent(ca);
        ma.pack(); 
    }//GEN-LAST:event_jButton4ActionPerformed
    
    public ImageIcon ResizeImage(String PathImage){
        ImageIcon myImage = new ImageIcon(PathImage);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(this.jLbAnh.getWidth()-260,this.jLbAnh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newmyimage = new ImageIcon(newImg);
        return newmyimage;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLbAnh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTFAuthor;
    private javax.swing.JTextField jTFBarcode;
    private javax.swing.JTextField jTFGenre;
    private javax.swing.JTextField jTFNamebook;
    private javax.swing.JTextField jTFNumberPage;
    private javax.swing.JTextField jTFPrice;
    private javax.swing.JTextField jTFQuantity;
    // End of variables declaration//GEN-END:variables
}
