/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewGUI;

import Controller.JCD;
import Model.Book;
import Model.Cart;
import Model.ShopBook;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DELL
 */
public class AdjustViewGUI extends javax.swing.JPanel {
    private ShopBook sb;
    private Cart car;
    private DefaultTableModel dTable;
    private mainAPP ma;
    private int index;
    private String pathAnh = null;
    
    public AdjustViewGUI(mainAPP ma) {
        sb = mainAPP.shB;
        car = mainAPP.ca;
        this.ma = ma;
        initComponents();
        this.showTable(sb.getShopSach());
    }

    public ShopBook getSb() {
        return sb;
    }

    public Cart getCar() {
        return car;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableShop = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLbImage = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLbBarcode = new javax.swing.JLabel();
        jTfBarcode = new javax.swing.JTextField();
        jLbNameBook = new javax.swing.JLabel();
        jTfNameBook = new javax.swing.JTextField();
        jLbAuthor = new javax.swing.JLabel();
        jTfAuthor = new javax.swing.JTextField();
        jLbGenre = new javax.swing.JLabel();
        jTfGenre = new javax.swing.JTextField();
        jLbNumberPage = new javax.swing.JLabel();
        jTfNumberPage = new javax.swing.JTextField();
        jLbQuantity = new javax.swing.JLabel();
        jTfQuantity = new javax.swing.JTextField();
        jLbPrice = new javax.swing.JLabel();
        jTfPrice = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jComboBoxPrice = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("<< BACK");
        jButton4.setActionCommand("BackButton");
        jButton4.setPreferredSize(new java.awt.Dimension(150, 75));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton4);

        jPanel1.add(jPanel12, java.awt.BorderLayout.LINE_START);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Adjust");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel13.add(jLabel2);

        jPanel1.add(jPanel13, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jTableShop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableShopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableShop);

        jPanel3.add(jScrollPane1);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jLbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageBook/HarryChiecCoc.jpg"))); // NOI18N
        jLbImage.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 180, 1, 270, new java.awt.Color(0, 0, 0)));
        jLbImage.setPreferredSize(new java.awt.Dimension(593, 352));
        jPanel4.add(jLbImage);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jPanel6.setLayout(new java.awt.BorderLayout());

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Change Image");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton5);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Confirm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3);

        jPanel6.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jPanel10.setLayout(new java.awt.GridLayout(7, 2));

        jLbBarcode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbBarcode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLbBarcode.setText("Barcode");
        jLbBarcode.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 30, new java.awt.Color(204, 204, 204)));
        jPanel10.add(jLbBarcode);

        jTfBarcode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTfBarcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(jTfBarcode);

        jLbNameBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbNameBook.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLbNameBook.setText("Name Book");
        jLbNameBook.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 30, new java.awt.Color(204, 204, 204)));
        jPanel10.add(jLbNameBook);

        jTfNameBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTfNameBook.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(jTfNameBook);

        jLbAuthor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbAuthor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLbAuthor.setText("Author");
        jLbAuthor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 30, new java.awt.Color(204, 204, 204)));
        jPanel10.add(jLbAuthor);

        jTfAuthor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTfAuthor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(jTfAuthor);

        jLbGenre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbGenre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLbGenre.setText("Genre");
        jLbGenre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 30, new java.awt.Color(204, 204, 204)));
        jPanel10.add(jLbGenre);

        jTfGenre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTfGenre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(jTfGenre);

        jLbNumberPage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbNumberPage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLbNumberPage.setText("Number page");
        jLbNumberPage.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 30, new java.awt.Color(204, 204, 204)));
        jPanel10.add(jLbNumberPage);

        jTfNumberPage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTfNumberPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(jTfNumberPage);

        jLbQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbQuantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLbQuantity.setText("Quantity");
        jLbQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 30, new java.awt.Color(204, 204, 204)));
        jPanel10.add(jLbQuantity);

        jTfQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTfQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(jTfQuantity);

        jLbPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLbPrice.setText("Price");
        jLbPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 30, new java.awt.Color(204, 204, 204)));
        jPanel10.add(jLbPrice);

        jTfPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTfPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(jTfPrice);

        jPanel6.add(jPanel10, java.awt.BorderLayout.CENTER);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Adjust Information Book");
        jPanel11.add(jLabel16);

        jPanel6.add(jPanel11, java.awt.BorderLayout.PAGE_START);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2);

        jComboBoxPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBoxPrice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Shop", "Less than 100.000đ", "from 100.000đ to 300.000đ", "from 300.000đ to 500.000đ", "greater than 500.000đ" }));
        jPanel8.add(jComboBoxPrice);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel5.add(jPanel7);

        jPanel4.add(jPanel5);

        jPanel3.add(jPanel4);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        for(int i=0; i< dTable.getRowCount() ;i++){   
            if(dTable.getValueAt(i, 7).equals(Boolean.TRUE)){
                new JCD().deleteBook(sb.getShopSach().get(i));
                sb.getShopSach().remove(sb.getShopSach().get(i));
            }
        }
        
        dTable.setRowCount(0);
        this.showTable(sb.getShopSach());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableShopMouseClicked
        index = jTableShop.getSelectedRow();
        TableModel model = jTableShop.getModel();
        String pathImage = sb.getShopSach().get(index).getPathimage();
        this.jLbImage.setIcon(this.ResizeImage(pathImage));
        
        this.jTfBarcode.setText(sb.getShopSach().get(index).getBarcode());
        this.jTfNameBook.setText(sb.getShopSach().get(index).getNameBook());
        this.jTfAuthor.setText(sb.getShopSach().get(index).getAuthor());
        this.jTfGenre.setText(sb.getShopSach().get(index).getGenre());
        this.jTfNumberPage.setText(sb.getShopSach().get(index).getNumberPage()+"");
        this.jTfQuantity.setText(sb.getShopSach().get(index).getQuantity()+"");
        this.jTfPrice.setText(sb.getShopSach().get(index).getPrice()+"");
   
    }//GEN-LAST:event_jTableShopMouseClicked

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = jComboBoxPrice.getSelectedIndex();
        switch(index){
            case 0:
                this.showTable(sb.getShopSach());
                break;
            case 1:
                dTable.setRowCount(0);
                ArrayList<Book> newshp0 = sb.searchBookbyPrice(sb.getShopSach(), b -> b.getPrice()<100000);
                this.showTable(newshp0);
                break;
            case 2:
                dTable.setRowCount(0);
                ArrayList<Book> newshp1 = sb.searchBookbyPrice(sb.getShopSach(), b -> b.getPrice()>=100000 && b.getPrice()<300000);
                this.showTable(newshp1);
                break;
            case 3:
                dTable.setRowCount(0);
                ArrayList<Book> newshp2 = sb.searchBookbyPrice(sb.getShopSach(), b -> b.getPrice()>=300000 && b.getPrice()<=500000);
                this.showTable(newshp2);
                break;
            case 4:
                dTable.setRowCount(0);
                ArrayList<Book> newshp3 = sb.searchBookbyPrice(sb.getShopSach(), b -> b.getPrice()>500000);
                this.showTable(newshp3);
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ma.setVisible(true);
        ChoiceAdd ca = new ChoiceAdd(ma);
        ma.getjSplitPane1().setRightComponent(ca);
        ma.pack();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            sb.getShopSach().get(index).setBarcode(jTfBarcode.getText());
            sb.getShopSach().get(index).setNameBook(jTfNameBook.getText());
            sb.getShopSach().get(index).setAuthor(jTfAuthor.getText());
            sb.getShopSach().get(index).setGenre(jTfGenre.getText());
            sb.getShopSach().get(index).setNumberPage(Integer.parseInt(jTfNumberPage.getText()));
            sb.getShopSach().get(index).setQuantity(Integer.parseInt(jTfQuantity.getText()));
            sb.getShopSach().get(index).setPrice(Double.parseDouble(jTfPrice.getText()));
            if(this.pathAnh != null) sb.getShopSach().get(index).setPathimage(this.pathAnh);
            
            JOptionPane.showMessageDialog(this, "Adjust information Successfully !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Input data");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFileChooser f= new JFileChooser("C:\\Users\\DELL\\Documents\\NetBeansProjects\\BookShopOnline\\src\\ImageBook");
        f.setDialogTitle("Open File");
        f.showOpenDialog(null);
        File nameImage = f.getSelectedFile();
        this.pathAnh = nameImage.getAbsolutePath();
        this.jLbImage.setIcon(this.ResizeImage(this.pathAnh));

    }//GEN-LAST:event_jButton5ActionPerformed
    
    public ImageIcon ResizeImage(String PathImage){
        ImageIcon myImage = new ImageIcon(PathImage);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(this.jLbImage.getWidth()-450,this.jLbImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newmyimage = new ImageIcon(newImg);
        return newmyimage;
    }
    
    public void showTable(ArrayList<Book> shp){
        dTable = new DefaultTableModel(sb.getData(shp),new Book().getTitle("Delete")){
            @Override
            public boolean isCellEditable(int row, int column) {
                return column==7;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if(columnIndex==7) return Boolean.class; 
                else return String.class;
            }
            
        };
        jTableShop.setModel(dTable);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBoxPrice;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbAuthor;
    private javax.swing.JLabel jLbBarcode;
    private javax.swing.JLabel jLbGenre;
    private javax.swing.JLabel jLbImage;
    private javax.swing.JLabel jLbNameBook;
    private javax.swing.JLabel jLbNumberPage;
    private javax.swing.JLabel jLbPrice;
    private javax.swing.JLabel jLbQuantity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableShop;
    private javax.swing.JTextField jTfAuthor;
    private javax.swing.JTextField jTfBarcode;
    private javax.swing.JTextField jTfGenre;
    private javax.swing.JTextField jTfNameBook;
    private javax.swing.JTextField jTfNumberPage;
    private javax.swing.JTextField jTfPrice;
    private javax.swing.JTextField jTfQuantity;
    // End of variables declaration//GEN-END:variables
}
