/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package viewGUI;

import Controller.JCD;
import Model.Book;
import Model.Cart;
import Model.ShopBook;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class CartViewGUI extends javax.swing.JPanel {

    private ShopBook shB;
    private Cart ca;
    private DefaultTableModel dTable;
     
    public CartViewGUI() {
        this.shB = mainAPP.shB;
        this.ca = mainAPP.ca;
        initComponents();
        this.showTable();
   
    }

    public ShopBook getShB() {
        return shB;
    }

    public Cart getCa() {
        return ca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCart = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Your Cart");
        jPanel1.add(jLabel2);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCart);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Book> bookSelected = new ArrayList<>();
        for(int i=0; i<dTable.getRowCount(); i++){
            if(dTable.getValueAt(i, 7).equals(Boolean.TRUE))
                bookSelected.add(ca.getBasket().get(i));
        }
        
        int i=0;
        for (Book bo : bookSelected) {
            shB.removeBook(bo, ca);
            dTable.setValueAt(Boolean.FALSE, i++, 7);
        }
        dTable.setRowCount(0);
        this.showTable();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void showTable(){
        dTable = new DefaultTableModel(shB.getData(ca.getBasket()),new Book().getTitle("Remove")){
            @Override
            public boolean isCellEditable(int row, int column) {
                return column==7;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if(columnIndex==7) return Boolean.class;
                else return String.class;
            }
            
        };
        jTableCart.setModel(dTable);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCart;
    // End of variables declaration//GEN-END:variables
}
