/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controller;

import Model.DatabaseAccount;
import View.LoginView;
import View.RegisterView;
import javax.swing.ImageIcon;

/**
 *
 * @author DELL
 */
public class FirstView extends javax.swing.JFrame {
    public static DatabaseAccount da  = new DatabaseAccount();
    ImageIcon ha = new ImageIcon("FirstViewImage.jpg");
    public static ImageIcon icon = new ImageIcon("Iconshop.png");
    
    public FirstView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(icon.getImage());
        jLabel1.setIcon(ha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jbLogin = new javax.swing.JButton();
        jbRegister = new javax.swing.JButton();
        jbIntro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shopping Online");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel2.setText("VINCENZO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 170, -1));

        jbLogin.setBackground(new java.awt.Color(255, 255, 51));
        jbLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jbLogin.setText("LOGIN");
        jbLogin.setBorderPainted(false);
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 140, 50));

        jbRegister.setBackground(new java.awt.Color(255, 255, 51));
        jbRegister.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jbRegister.setText("REGISTER");
        jbRegister.setBorderPainted(false);
        jbRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jbRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 140, 50));

        jbIntro.setBackground(new java.awt.Color(255, 255, 51));
        jbIntro.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jbIntro.setText("INTRODUCE");
        jbIntro.setBorderPainted(false);
        getContentPane().add(jbIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 140, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Shopping online");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 467, 593));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        LoginView lv = new LoginView();
        lv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbLoginActionPerformed

    private void jbRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegisterActionPerformed
        RegisterView rv = new RegisterView();
        rv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbIntro;
    private javax.swing.JButton jbLogin;
    private javax.swing.JButton jbRegister;
    // End of variables declaration//GEN-END:variables
}
